version: '3'
services:
  shadowsocks:
    image: hopher/shadowsocks-libev:latest
    expose:
      - 8388/tcp
      - 8388/udp
    container_name: my_shadowsocks
 
    build:
      context: .
       
       
    environment:
      - METHOD=aes-256-gcm  # 加密方法
      - PASSWORD=9MLSpPmNt  # 密码
   
    restart: always