version: '3'
services:
  shadowsocks:
    image: hopher/shadowsocks-libev:latest
    
    container_name: my_shadowsocks
 
    build:
      context: .
      dockerfile: Dockerfile
 
    ports:
        - 8388
      
    environment:
      - METHOD=aes-256-gcm  # 加密方法
      - PASSWORD=9MLSpPmNt  # 密码
   
    restart: always